---
- name: Delete a keypair
  hosts: localhost
  gather_facts: False

  tasks:
    - name: Execute tasks to get the project and credential information
      include_tasks: get_project_cred_info_tasks.yml

    - name: Delete EC2 key pair
      ec2_key:
        name: "{{ aws_keypair }}"
        profile: "{{ aws_profile }}"
        state: absent
      register: keyinfo

    - name: Delete the key file
      file:
        path: "{{ aws_keypair_key_file }}"
        state: absent
