---
- name: Create a keypair
  hosts: localhost
  gather_facts: False

  tasks:
    - name: Execute tasks to get the project and credential information
      include_tasks: get_project_cred_info_tasks.yml

    - name: Create EC2 key pair
      ec2_key:
        name: "{{ aws_keypair }}"
        profile: "{{ aws_profile }}"
      register: keyinfo

    - name: Populate the key file
      copy:
        content: "{{ keyinfo.key.private_key }}"
        dest: "{{ aws_keypair_key_file }}"
        mode: "0400"
