---
# tasks file for nfs_svr
- name: Ensure NFS and firewalld software is installed
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - nfs-utils
    - firewalld

- name: Ensure firewalld service is started and enabled on boot
  service:
    enabled: yes
    name: firewalld
    state: started

- name: Ensure firewall is configured for NFS
  firewalld:
    immediate: True
    permanent: True
    service: "{{ item }}"
    state: enabled
  with_items:
    - nfs
    - rpc-bind
    - mountd

- name: Ensure NFS service is started and enabled on boot
  service:
    enabled: yes
    name: nfs-server
    state: started
